#!/bin/bash
exec 100>/tmp/$(basename $0 .sh)-lock
flock -n 100
if [ $? -ne 0 ]; then
        echo "Error!"
        exit 1
fi

XDG_SESSION_TYPE=wayland
XDG_CURRENT_DESKTOP=sway
XDG_CURRENT_SESSION=sway
LIBSEAT_BACKEND=logind
QT_QPA_PLATFORM=wayland
GDK_DPI_SCALE=0.9
QT_SCALE_FACTOR=0.9
MOZ_ENABLE_WAYLAND=1
WINIT_UNIX_BACKEND=x11

export XDG_SESSION_TYPE XDG_CURRENT_DESKTOP XDG_CURRENT_SESSION LIBSEAT_BACKEND QT_QPA_PLATFORM GDK_DPI_SCALE QT_SCALE_FACTOR MOZ_ENABLE_WAYLAND WINIT_UNIX_BACKEND;

exec sway
